site_name: My Docs
theme:
    name: readthedocs
    feature:
      - navigation.sections
      - navigation.indexes
      - navigation.expand
      - toc.follow
   
nav:
    - Home: index.md
    - Excercise: Excercise.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


